<img style="float: left;;" src='Figures/iteso.jpg' width="100" height="200"/></a>

# <center> <font color= #000047> Repaso Python y Librerías </font> </center>



## Introducción

Python es un lenguaje de software libre, no tipado, interpretado y orientado a objetos. Se presenta como principal elección entre los lenguajes utilizados para aplicaciones de inteligencia artificial, particularmente de machine learning, junto con R, Matlab y Octave (dependiendo la comunidad que lo use).

Posee un enorme ecosistema de librerías de machine learning. Esto sumado a su flexibilidad y su simpleza de uso hacen que sea uno de los lenguajes más populares para la computación científica.

Algunos IDEs: Jupyter (web), Pycharm, Rodeo.


Info adicional:

* [Markdown](https://daringfireball.net/projects/markdown/) es un conversor de texto plano a HTML. En los notebooks funciona como suerte de versión "liviana" de LaTex. Se usa en sitios como Slack, github (para los README), reddit.
* [LaTex](http://www.latex-project.org/) es un sistema de tipografía de alta calidad, que permite armar documentos con una sintaxis predefinida. Su sintaxis es mucho más verborrágica comparado con las herramientas típicas de ofimática, pero es mucho más flexible. A LaTex en los notebooks se lo utiliza principalmente para fórmulas.

Info adicional sobre LaTex, para aquellos interesados:
* Para armar documentos completos en LaTex de forma sencilla una buena alternativa es [Overleaf](https://www.overleaf.com/) (editor LaTex Web colaborativo). Por su parte, la alternativa que recomendamos es descargarlo mediante TexLive (en Debian/Ubuntu/Mint lo descargan con *sudo apt-get install texlive-full* (pesa 4Gb)) y editar los documentos mediante [Atom](http://atom.io/) y sus paquetes *latex* y *language-latex*

Para sus explicaciones en texto, jupyter por defecto utiliza Markdown. Para utilizar LaTex en un notebook, debe encerrarse la sentencia en \\$ ecuación \\$ para ecuaciones en la misma línea o bien entre \\$\\$ ecuación \\$\\$ para ecuaciones en una nueva línea.

Ejemplo $$\lim_{h \to 0} \frac{f(a+h)-f(a)}{h}$$

## Mi primera ecuacion:

$$x = x^2 + 2*x$$
$$x = \frac{x^2}{2*x}$$

x^2 = x +2

Veamos algo de código al ver una de las estructuras principales de Python...

In [1]:
# estructura fundamental de python: listas
lista = [1,2,3,4]
lista

[1, 2, 3, 4]

In [2]:
type(lista)

list

In [5]:
lista.append(1)

In [6]:
lista

[1, 2, 3, 4, 1]

In [7]:
# principal característica: listas completamente flexibles
lista2= lista + lista
lista2

[1, 2, 3, 4, 1, 1, 2, 3, 4, 1]

In [8]:
lista3=[1,'asd', 0.5, len]
lista3

[1, 'asd', 0.5, <function len(obj, /)>]

In [9]:
# con len() podemos ver las dimensiones de la lista
len(lista3)

4

In [14]:
# cuál es el elemento con índice 1 de la lista?
lista3[0]

1

In [15]:
lista2

[1, 2, 3, 4, 1, 1, 2, 3, 4, 1]

In [16]:
lista2[2:7]

[3, 4, 1, 1, 2]

In [17]:
lista2[7:10]

[3, 4, 1]

In [18]:
# de manera similar...
lista2[7:]

[3, 4, 1]

In [20]:
lista2[0:4]

[1, 2, 3, 4]

In [21]:
lista2[:4]

[1, 2, 3, 4]

In [30]:
lista2[2:-5]

[3, 4, 1]

In [31]:
lista2[-1]

1

In [32]:
# o también...
mat = [[1,2,3], [2,5,6], [0,1,2]]
mat


[[1, 2, 3], [2, 5, 6], [0, 1, 2]]

In [37]:
mat[0][1]

2

## Algunos bloques y estructuras básicas

### if

In [38]:
x = 2
y = 5

In [ ]:
# >=, <=, >,<, ==, !=

In [39]:
x>=y

False

In [40]:
x==y

False

In [41]:
x<=y

True

In [42]:
if (x<=y):
    print(x)
else: 
    print(y)
    

2


In [45]:
x, y

(2, 5)

In [44]:
if (x>=y):
    print(x)
elif (y<1): 
    print(y)
else: 
    print('valor no correcto')

valor no correcto


## Tuplas

In [46]:
x = (2,3,5,6,78)
x

(2, 3, 5, 6, 78)

In [47]:
lista

[1, 2, 3, 4, 1]

In [48]:
lista[0] = 10
lista

[10, 2, 3, 4, 1]

In [49]:
x[0] = 10

TypeError: 'tuple' object does not support item assignment

In [50]:
cadena = "Hola a mi primera clase de SIMAT"
cadena

'Hola a mi primera clase de SIMAT'

In [52]:
cadena[0:7]

'Hola a '

### for

In [53]:
# for opera normalmente sobre rangos, listas u otro tipo de iterables
for i in range(2):
    print(i)

0
1


In [55]:
lista

[10, 2, 3, 4, 1]

In [54]:
for l in lista:
    print(l)

10
2
3
4
1


In [56]:
for l in x:
    print(l)

2
3
5
6
78


In [58]:
for a in cadena:
    print(a)

H
o
l
a
 
a
 
m
i
 
p
r
i
m
e
r
a
 
c
l
a
s
e
 
d
e
 
S
I
M
A
T


In [60]:
lista4 = []
for l in lista:
    if l<=2:
        lista4.append(l)
    else:
        print(f'{l} es mayor a 5')
lista4

10 es mayor a 5
3 es mayor a 5
4 es mayor a 5


[2, 1]

### dict

In [61]:
a = {'c_1': 1, 'c_2':2, 'c_3': 3}
a

{'c_1': 1, 'c_2': 2, 'c_3': 3}

In [62]:
a2 = {'c_1': '1', 'c_2':'2', 'c_3': '3'}
a2

{'c_1': '1', 'c_2': '2', 'c_3': '3'}

In [64]:
a3 = {'c_1': 1.0, 'c_2':2.0, 'c_3': 3.0}
a3

{'c_1': 1.0, 'c_2': 2.0, 'c_3': 3.0}

In [66]:
a2['c_1'],a['c_1'], a3['c_1']

('1', 1, 1.0)

In [67]:
a.values()

dict_values([1, 2, 3])

In [68]:
a.keys()

dict_keys(['c_1', 'c_2', 'c_3'])

In [69]:
for i in a.values():
    print(i)

1
2
3


In [70]:
for i in a.keys():
    print(i)

c_1
c_2
c_3


In [71]:
for item in a.items():
    print(item)

('c_1', 1)
('c_2', 2)
('c_3', 3)


In [72]:
for key,val in a.items():
    print(key, val)

c_1 1
c_2 2
c_3 3


### tuple

Representan estructuras inmutables

In [73]:
tupla1 = 1,2,3,4,5
tupla1

(1, 2, 3, 4, 5)

In [74]:
tupla2= (1,2,3,4,5)
tupla2

(1, 2, 3, 4, 5)

In [75]:
tupla2[0] = 2

TypeError: 'tuple' object does not support item assignment

## Funciones en Python

In [76]:
def funcion1(x,y):
    x1 = x**2 + 2*x
    y2 = y**2 + x1
    
    return x1,y2
    

In [77]:
funcion1(1,5)

(3, 28)

In [78]:
def funcion1(x=1,y=1):
    x1 = x**2 + 2*x
    y2 = y**2 + x1
    
    return x1,y2

In [79]:
funcion1()

(3, 4)

In [80]:
funcion1(x=6,y=10)

(48, 148)

In [81]:
funcion1(y=10, x= 3)

(15, 115)

In [82]:
funcion1(10,3)

(120, 129)

### Ejercicios:

1.- Escribir un programa que almacene en una liusta los números del 1 al 10, y los muestre en pantalla en orden inverso separados por coma.

> lista1 --->1,...,10
> lista2 ---->10,9,...,1



2.- escribir una función que reciba una cadena de caracteres y que muestre si esta cadena de caracteres es un palíndromo.

### 1.- Solución: 

In [84]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

In [86]:
type(range(1,11))

range

In [83]:
lista1=list(range(1,11))
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [87]:
#10,9,8,7,6,5,4,3,2,1
n=0
lista2=[]
while(abs(n)<10):
    a=lista1[-1+n]
    lista2.append(a)
    n=n-1

print(lista2)


[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [90]:
list(range(10,0,-1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [98]:
lista1
lista2 =[]
for i in range(10,0,-1):
    lista2.append(lista1[i-1])
    print(lista1[i-1])

10
9
8
7
6
5
4
3
2
1


In [99]:
lista2

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [101]:
lista1.reverse()

In [102]:
lista1

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [103]:
lista1[::-1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [110]:
lista3 = lista1[::-1]
lista3

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [125]:
s='anita lava la tina'
s='AniTas LaVa lA TINA'

In [126]:
s2 = s.replace(" ","").lower()

In [127]:
s2

'anitaslavalatina'

In [128]:
s2[::-1] == s2

False

In [129]:
x = 2

In [131]:
type(x)

int

In [135]:
help(int)

Help on class int in module builtins:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Built-in subclasses:
 |      bool
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      self != 

In [137]:
x.as_integer_ratio()

(3, 1)

## 2.- Solución:



In [113]:
import unicodedata
def palindromo(cadena):
    cadena = unicodedata.normalize('NFKD', cadena).encode('ascii', 'ignore').decode('utf-8', 'ignore')
    lista_11SN = []  # Serivirá para almancenar la palabra original pero sin espacios vacios
    lista_21SN = []  #Lo mismo que la anterior la palabra invertida sin espacios
    lista_4 = []     #Lista con cada letra de la palabra original
    lista_5 = []     #Lista con cada letra pero en orden inverso
    b = len(cadena)
    n = 0

    while n<b:

        c = cadena[0+n]

        lista_4.append(c)

        n = n + 1 

    if n == b:

        n=0

        while n < b:

            i = lista_4[-1-n]

            lista_5.append(i)

            n = n + 1

        if n == b:

            for string in lista_4:

                if string != "" and string != " ":

                    lista_11SN.append(string)

            for string in lista_5:

                if string != "" and string != " ":

                    lista_21SN.append(string)               

        cadena_1=''.join(lista_11SN)

        cadena_2=''.join(lista_21SN)

        cadena_11=cadena_1.lower()

        cadena_21=cadena_2.lower()

        if cadena_11 == cadena_21:

            print("La palabra/frase -->",cadena,"<--es un palíndromo")

        else:

            print("La palabra/frase -->",cadena,"<--no es un palíndromo")

    return(cadena_11,cadena_21,lista_11SN,lista_21SN)


SyntaxError: invalid character in identifier (Temp/ipykernel_37820/2661497478.py, line 3)

## Algunas librerías importantes

### numpy

Librería open-source que dota a Python de manejo de vectores y matrices, junto con un conjunto de librerías para procesarlas, asemejando a python al manejo estilo Matlab.

El bloque básico de numpy es el **ndarray**, un array multidimensional de elementos homogéneos y de tamaño fijo. A estos objetos no los creamos directamente, sino por un método destinado a tal efecto.


In [138]:
import numpy as np 

In [139]:
array = np.array([1,2,3,4,5,6,7])
array

array([1, 2, 3, 4, 5, 6, 7])

In [140]:
type(array)

numpy.ndarray

In [142]:
array = np.array((1,2,3,4,5,6,7))
array

array([1, 2, 3, 4, 5, 6, 7])

In [146]:
a = np.arange(5,10)
a

array([5, 6, 7, 8, 9])

In [148]:
M = np.array([[1,2,3],
               [2,3,4],
               [4,5,6]])

In [149]:
M

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [151]:
a.shape

(5,)

In [152]:
a.dtype

dtype('int32')

In [155]:
a.reshape(5,1)


array([[5],
       [6],
       [7],
       [8],
       [9]])

In [158]:
M

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [157]:
M.shape

(3, 3)

In [159]:
M.reshape(1,9)

array([[1, 2, 3, 2, 3, 4, 4, 5, 6]])

In [160]:
M.reshape(9,1)

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4],
       [4],
       [5],
       [6]])

In [162]:
M

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [161]:
M.T

array([[1, 2, 4],
       [2, 3, 5],
       [3, 4, 6]])

In [164]:
M.transpose(), M

(array([[1, 2, 4],
        [2, 3, 5],
        [3, 4, 6]]),
 array([[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]))

In [165]:
M2 = M.transpose()
M2

array([[1, 2, 4],
       [2, 3, 5],
       [3, 4, 6]])

In [166]:
M2 + M

array([[ 2,  4,  7],
       [ 4,  6,  9],
       [ 7,  9, 12]])

In [168]:
M2 - M

array([[ 0,  0,  1],
       [ 0,  0,  1],
       [-1, -1,  0]])

In [170]:
M2,M

(array([[1, 2, 4],
        [2, 3, 5],
        [3, 4, 6]]),
 array([[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]))

In [169]:
M2*M

array([[ 1,  4, 12],
       [ 4,  9, 20],
       [12, 20, 36]])

In [171]:
np.dot(M2,M)

array([[21, 28, 35],
       [28, 38, 48],
       [35, 48, 61]])

In [172]:
M2@M

array([[21, 28, 35],
       [28, 38, 48],
       [35, 48, 61]])

In [175]:
a

array([5, 6, 7, 8, 9])

In [174]:
# similarmente, no confundir la matriz que generamos con la lista de listas de python!!!
# son de dos tipos distintos
a + 2*a

array([15, 18, 21, 24, 27])

In [176]:
al = [5,6,7,8,9]

In [177]:
al + 2*al

[5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9]

In [178]:
# Principal ventaja de numpy: nos permite realizar fácil y eficientemente operaciones a nivel de lista
a

array([5, 6, 7, 8, 9])

In [179]:
a[2]

7

In [180]:
a[:4]

array([5, 6, 7, 8])

In [181]:
a[::2]

array([5, 7, 9])

In [182]:
a[:-1]

array([5, 6, 7, 8])

In [183]:
# pedimos los elementos de índice 2 y 3 de la segunda columna
# (Notar que 2:4 equivale al intervalo [2,4), es decir que el elemento de índice 4 está excluído)
M

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [184]:
M[1,1]

3

In [185]:
M[1:,1:]

array([[3, 4],
       [5, 6]])

In [188]:
M[:2,:2]

array([[1, 2],
       [2, 3]])

In [190]:
#[[1,3],
# [4,6]]
M[[0,0],[0,2],[2,0],[2,2]]

IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed

In [192]:
M

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [191]:
M[:3:2,:3:2]

array([[1, 3],
       [4, 6]])

In [194]:
# otra operación comúnmente usada para construir o cambiar matrices:
# np.reshape
M.reshape(9,1)

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4],
       [4],
       [5],
       [6]])

In [195]:
M.reshape(4,1)

ValueError: cannot reshape array of size 9 into shape (4,1)

In [200]:
10*np.ones((5,5))

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [202]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [203]:
np.random.random((5,4))

array([[0.83913157, 0.09238254, 0.74543733, 0.89047619],
       [0.56245588, 0.6925896 , 0.57751604, 0.74860367],
       [0.51712407, 0.49742766, 0.06113438, 0.41662321],
       [0.44270909, 0.8860337 , 0.48028272, 0.92193527],
       [0.36360003, 0.61405389, 0.0035176 , 0.24895711]])

In [206]:
arr1 = np.random.randint(1,100, size=(5,4))
arr1

array([[89,  6, 43, 19],
       [ 4, 36, 39, 56],
       [84, 13,  3, 69],
       [ 8, 94,  5, 55],
       [79, 89, 85, 15]])

In [208]:
arr1.sum(axis=0)

array([264, 238, 175, 214])

In [209]:
arr1.sum(axis=1)

array([157, 135, 169, 162, 268])

In [210]:
arr1.max()

94

In [211]:
arr1.min()

3

In [213]:
arr1.mean(axis=0)

array([52.8, 47.6, 35. , 42.8])

In [214]:
arr1.mean(axis=1)

array([39.25, 33.75, 42.25, 40.5 , 67.  ])

In [215]:
arr1.std()

33.165456426830616

## Ejercios:

1.- Crear una funcion que reciba un arreglo y retornar en otro arreglo los indices que no son ceros Probar con el siguiente arreglo: 
 (crear un arreglo con los siguientes valores) 
 > in: arr = [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]
 
 > out: arr_ind = [0,1,2,3,4,6,10,11,12,13,14]

In [ ]:
a  = [idx for idx, element in enumerate(arr) if element != 0]
type(a)

### matplotlib

matplotlib es la librería estándar para la visualización de datos, algo que resulta fundamental para machine learning. Es muy flexible y simple de usar. Se integra con jupyter, lo cual permite ver gráficos en un notebook.

La función principal de la misma es plot(), la cual toma un número variable de argumentos y grafica de forma tan simple como escribiendo plot(x,y)

### Definiendo funciones

Las funciones por defecto de Python son de mucha utilidad. Sin embargo, pronto nos daremos cuenta que sería más útil aún definir nuestras propias funciones para reutilizarlas cada vez que las necesitemos.

Por ejemplo, creemos una función que dados tres números, devuelva la mínima diferencia absoluta entre ellos

In [ ]:
# Explicar acá la forma de definir una función


Las funciones comienzan con la palabra clave `def`, y el código indentado luego de los dos puntos `:` se corre cuando la función es llamada.

`return` es otra parablra clave que sólo se asocia con funciones. Cuando Python se encuentra un `return`, termina la función inmediatamente y devuelve el valor que hay seguido del `return`.

¿Qué hace específicamente la función que escribimos?

In [ ]:
# Ejemplo: llamar la función unas 3 veces


Intentemos llamar `help` sobre la función

Bueno, Python tampoco es tan listo como para leer código y entregar una buena descripción de la función. Esto es trabajo del diseñador de la función: incluir la documentación.

¿Cómo se hace? (Recordar añadir un ejemplo)

In [ ]:
# Copiar y pegar la función, pero esta vez, incluir documentación de la misma


In [ ]:
# Volver a llamar el help


Muy bien. Ahora, podemos observar que podemos llamar esta función sobre diferentes números, incluso de diferentes tipos:

- Si todos son enteros, entonces nos retornará un entero.
- Si hay algún float, nos retornará un float.

In [ ]:
# Todos enteros


In [ ]:
# Uno o más floats


In [ ]:
# String: TypeError


####  Funciones que no devuelven

¿Qué pasa si no incluimos el `return` en nuestra función?

In [ ]:
# Ejemplo de función sin return


In [ ]:
# Llamar la función un par de veces


####  Argumentos por defecto

Modificar la función `saludo` para que tenga un argumento por defecto.

In [ ]:
# Función saludo con argumento por defecto


## Actividad:


### Numpy
**Ejercicio 1:**

1. Crear un vector con valores de 10 a 49.
2. Crear una función (recibe_vector) que reciba el vector y dentro de la función elevar al cuadrado a aquellos números divisibles por 3 y regresar esos numeros en un nuevo vector.
3. Redimensionar el vector que devuelve la función anterior en una matriz de 20x2.
4. Crear una nueva matriz de 2x10 y multiplicarla a la matriz anterior.
5. Obtener la transpuesta de la matriz resultante.

**Ejercicio 2:**

Se desea calcular el índice de masa corporal (IMC) de jugadores de un equipo de futbol. Los datos proporcionados corresponden a las listas de los nombres, altura y peso, tal como se muestra a continuación

In [ ]:
nombre= ['Bonifacio de Cifuentes',
'Ángel Machado Lara',
'Geraldo de Atienza',
'Onofre Posada Grande',
'Samu Cantón-Figuerola',
'Camilo Pol',
'Toni Galvez Lara',
'Lucho Manzano Rivas',
'Abraham Aroca',
'Anselmo Bartolomé Folch',
'Toni Inocencio Rozas Porras',
'Fausto Cortés-Arco',
'Baltasar Carreño Isern']

altura = [180, 215, 210, 210, 188, 176, 209, 200, 210, 188, 176, 209, 200]
peso = [69, 74, 72, 75, 68, 70, 71, 73, 69, 74, 72, 75, 68, 70, 71, 73]

El valor de IMC por cada jugador resulta de aplicar la fórmula:

$$IMC = \frac{peso(kg)}{altura(m)^2}$$

**Nota:** Los valores de altura están dados en centímetros por lo que deberá hacer laconversión a metros previo a la aplicación de la fórmula. Adicionalmente, una vez obtenido el IMC se solicita:

> a) Presentar el icm para cada jugador.

> b) Indicar en qué índice se encuentra el icm más alto y a qué jugador le pertenece.

> c) Calcular el promedio de los icm resultantes.

> d) Muestre los nombres de los jugadores en orden de su imc, desde el que tiene menorimc al que tiene mayor imc.